//! Nodes are the output of parsing.

use super::color::Paint;
use super::symbols::Symbol;
use crate::dimensions::AnyUnit;
use crate::font::TexSymbolType;
use crate::layout::{self, Style};

/// Nodes are the output of parsing a LateX formula ; they can then be arranged in space with [`crate::layout::engine::layout`].
// TODO: It might be worth letting the `Group` variant
//   to have an atomtype associated with it.  By default,
//   it will be a `Ordinary`.
#[derive(Debug, PartialEq, Clone)]
pub enum ParseNode {
    /// A simple symbol like 'x' or 'α'
    Symbol(Symbol),
    /// A group of nodes enclosed by '\left' and '\right'
    Delimited(Delimited),
    /// A delimiter with a user-specified height (created by `\bigl`, `\bigg`, etc.)
    ExtendedDelimiter(ExtendedDelimiter),
    /// A group of nodes enclosed by a '\sqrt' square root radical.
    Radical(Radical),
    /// A fraction with some nodes as numerator and some other nodes in the denominator
    GenFraction(GenFraction),
    /// A node with superscripts or/and subscripts
    Scripts(Scripts),
    /// A rule (i.e. a uniformly filled line)
    Rule(Rule),
    /// Some (positive or negative) spacing between groups of nodes
    Kerning(AnyUnit),
    /// An accent over a certain groups of nodes
    Accent(Accent),
    /// A style (text cramped) to apply over a certain group of nodes
    Style(Style),
    /// Underline and overlines
    FontEffect(FontEffect),
    /// A span of normal text without special math symbol replacement, spacing, etc.
    PlainText(PlainText),
    /// A change in the type of atoms
    AtomChange(AtomChange),
    /// A change in color
    Color(Color),
    /// A group of nodes
    Group(Vec<ParseNode>),
    /// Nodes stacked on top of each other with no alignment (the \substack command)
    Stack(Stack),
    /// Array of formulas, with some alignment
    Array(Array),
    /// An invisible node, used only for spacing rule in `\begin{aligned} .. \end{aligned}` environments
    DummyNode(DummyNode), // // DEPRECATED
                          // /// Extend a glyph vertically ; this parse node is generated by the fictional \vextend LateX command.
                          // /// It appears to be otherwise ignored
                          // Extend(char, AnyUnit),
}

/// The collection of column formatting for an array.  This includes the horizontal
/// alignment for each column in an array along with optional vertical bars, and nodes to include between each column
/// positioned to the right of the last column.
#[derive(Debug, Clone, PartialEq)]
pub struct ArrayColumnsFormatting {
    /// The formatting specifications for each column
    pub alignment: Vec<ArrayColumnAlign>,

    /// Separators between each column, could be vertical bars or
    pub separators: Vec<Vec<ColSeparator>>,
}

/// Array contents are the body of the enviornment.  Columns are seperated
/// by `&` and a newline is terminated by either:
///   - `\\[unit]`
///   - `\cr[unit]`
///     where a `[unit]` is any recognized dimension which will add (or subtract)
///     space between the rows.  Note, the last line termination is ignored
///     if the a line is empty.
pub type CellContent = Vec<ParseNode>;

// TODO: since we use default values, we should make the argument optional?
/// Array column alignent.  These are parsed as a required macro argument
/// for the array enviornment. The default value is `Centered`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ArrayColumnAlign {
    /// Column is centered
    #[default]
    Centered,

    /// Column is left aligned.
    Left,

    /// Column is right aligned.
    Right,
}

/// An array of nodes as created by e.g. `\begin{array}{c} .. \end{array}`, `\begin{pmatrix} .. \end{pmatrix}` or `\begin{aligned} .. \end{aligned}`
#[derive(Debug, Clone, PartialEq)]
pub struct Array {
    /// The alignment arguments (clr) for each row, plus separators (bars and @-expressions).  Default: center.
    pub col_format: ArrayColumnsFormatting,

    /// A collection of rows.  Each row consists of one `Vec<Expression>`.
    pub rows: Vec<Vec<CellContent>>,

    /// The left delimiter for the array (optional).
    pub left_delimiter: Option<Symbol>,

    /// The right delimiter for the array (optional).
    pub right_delimiter: Option<Symbol>,

    /// Whether to add separation between rows.  
    /// In `\begin{aligned} .. \end{aligned}` environments, there is more space between lines
    pub extra_row_sep: bool,

    /// Layout style to render cells with  
    /// In `\begin{aligned} .. \end{aligned}` environments, the cells are rendered display style, even
    /// when they are embedded in an environment with text style.
    /// In `\begin{array} .. \end{array}`, they are rendered in text style
    pub cell_layout_style: layout::Style,
}

/// An enum for the differents elements that can be used to separate columns in TeX.
#[derive(Debug, Clone, PartialEq)]
pub enum ColSeparator {
    /// A certain number of vertical bars.
    VerticalBars(u8),
    /// Nodes to be put between every column.
    AtExpression(Vec<ParseNode>),
}

impl ColSeparator {
    /// Checks if the separator is a set of vertical bars.
    pub fn is_vert_bars(&self) -> bool {
        matches!(self, Self::VerticalBars(_))
    }
}

/// Cf [`ParseNode::Stack`]
#[derive(Debug, PartialEq, Clone)]
pub struct Stack {
    /// The type of the resulting stack.
    pub atom_type: TexSymbolType,
    /// Lines of formulas to stack on top of each other.
    pub lines: Vec<Vec<ParseNode>>,
}

/// Cf [`ParseNode::Delimited`]
#[derive(Debug, PartialEq, Clone)]
pub struct Delimited {
    /// Symbols after \left, \middle and \right in the order that they appear
    delimiters: Vec<Symbol>,
    /// Nodes delimited by left, middle and right in the order that they appear
    inners: Vec<Vec<ParseNode>>,
}

impl Delimited {
    /// Creates new [`Delimited`] from the given symbols and the given delimited group.
    pub fn new(delimiters: Vec<Symbol>, inners: Vec<Vec<ParseNode>>) -> Self {
        Self { delimiters, inners }
    }

    /// Symbols after \left, \middle and \right in the order that they appear.
    pub fn delimiters(&self) -> &[Symbol] {
        self.delimiters.as_ref()
    }

    /// Nodes delimited by left, middle and right in the order that they appear.
    pub fn inners(&self) -> &[Vec<ParseNode>] {
        self.inners.as_ref()
    }
}

/// Cf [`ParseNode::ExtendedDelimiter`]
#[derive(Debug, PartialEq, Clone)]
pub struct ExtendedDelimiter {
    /// Symbol to use, its atom type is the atom type of the whole expression
    pub symbol: Symbol,
    /// Height of the content this delimiter is meant to enclose  
    /// The shape and size of an extended delimiter like `(` are computed by assuming it will enclose a content of size `height_enclosed_content`,
    /// as if it were in `\left(\rule{0pt}{<height_enclosed_content>}\right.`
    pub height_enclosed_content: AnyUnit,
}

impl ExtendedDelimiter {
    /// Creates a new delimiter from t
    pub fn new(symbol: Symbol, height_enclosed_content: AnyUnit) -> Self {
        Self {
            symbol,
            height_enclosed_content,
        }
    }
}

/// Cf [`ParseNode::Scripts`]
#[derive(Debug, PartialEq, Clone)]
pub struct Scripts {
    /// Nodes at the base.
    pub base: Option<Box<ParseNode>>,
    /// Superscripted nodes.
    pub superscript: Option<Vec<ParseNode>>,
    /// Subscripted nodes.
    pub subscript: Option<Vec<ParseNode>>,
}

impl Scripts {
    /// Retrieves the superscript if argument is true, otherwise the subscript. Useful for writing functions that work for both subscript and superscripts.
    pub fn get_script(&mut self, superscript: bool) -> &mut Option<Vec<ParseNode>> {
        if superscript {
            &mut self.superscript
        } else {
            &mut self.subscript
        }
    }
}

/// Cf [`ParseNode::DummyNode`]
#[derive(Clone, Debug, PartialEq)]
pub struct DummyNode {
    /// Atom type of the dummy node
    pub at: TexSymbolType,
}

/// Cf [`ParseNode::AtomChange`]
#[derive(Clone, Debug, PartialEq)]
pub struct AtomChange {
    /// New atom type
    pub at: TexSymbolType,
    /// Inner nodes
    pub inner: Vec<ParseNode>,
}

/// Cf [`ParseNode::PlainText`]
#[derive(Clone, Debug, PartialEq)]
pub struct PlainText {
    /// Text to be renderered
    pub text: String,
}

/// Cf [`ParseNode::Accent`]
#[derive(Clone, Debug, PartialEq)]
pub struct Accent {
    /// The accent to place on top of the nodes.
    pub symbol: Symbol,
    /// The nodes "below" the accent.
    pub nucleus: Vec<ParseNode>,
    /// Whether or not the accent should extend horizontally if the nucleus is wide.
    pub extend: bool,
    /// Whether the accent is placed under the nucleus
    pub under: bool,
}

/// Cf [`ParseNode::Rule`]. While intended to be used as lines, rules can in fact be any rectangle.
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Rule {
    /// width of the rule
    pub width: AnyUnit,
    /// height of the rule
    pub height: AnyUnit,
    //pub depth:  Unit,
}

/// A font effect. Currently, simply means that that the nodes will be underlined
#[derive(Clone, PartialEq, Debug)]
pub struct FontEffect {
    /// Nodes to be underlined
    pub inner: Vec<ParseNode>,
}

/// Cf [`ParseNode::Radical`]
#[derive(Debug, PartialEq, Clone)]
pub struct Radical {
    /// The nodes that the root covers
    pub inner: Vec<ParseNode>,
    /// The character used to represent the radical (typically U+221A '√', but also '∛' U+221B, etc.)
    pub character: char,
    /// Optional index for nth root (e.g. `\sqrt[3]{x}` has index `3`)
    pub index: Option<Vec<ParseNode>>,
    // pub superscript: Vec<ParseNode>,
}

/// Cf [`ParseNode::GenFraction`]
#[derive(Debug, PartialEq, Clone)]
pub struct GenFraction {
    /// nodes at the numerator.
    pub numerator: Vec<ParseNode>,
    /// nodes at the denominator.
    pub denominator: Vec<ParseNode>,
    /// thickness of the fraction line.
    pub bar_thickness: BarThickness,
    /// symbol opening the fraction.
    pub left_delimiter: Option<Symbol>,
    /// symbol closing the fraction.
    pub right_delimiter: Option<Symbol>,
    /// style for the whole fraction.
    pub style: MathStyle,
}

/// Cf [`ParseNode::Color`]
#[derive(Debug, Clone, PartialEq)]
pub struct Color {
    /// new color for the children nodes
    pub color: Paint,
    /// children nodes
    pub inner: Vec<ParseNode>,
}

/// Type of thickness for fraction and binomials
#[derive(Debug, Copy, Clone, PartialEq)]
pub enum BarThickness {
    /// A default thickness
    Default,
    /// No bar
    None,
    /// A custom thickness
    Unit(AnyUnit),
}

/// Style of maths
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum MathStyle {
    /// default style ; characters are slanted.
    Display,
    /// text style ; characters are straight.
    Text,
    /// keep style inherited from higher nodes.
    NoChange,
}

impl ParseNode {
    /// if parse node is a single symbol, returns it. Otherwise, `None`.
    pub fn is_symbol(&self) -> Option<Symbol> {
        match *self {
            ParseNode::Symbol(sym) => Some(sym),
            ParseNode::Scripts(Scripts { ref base, .. }) => {
                base.as_ref().and_then(|b| b.is_symbol())
            }
            ParseNode::Accent(ref acc) => is_symbol(&acc.nucleus),
            ParseNode::AtomChange(ref ac) => is_symbol(&ac.inner),
            ParseNode::Color(ref clr) => is_symbol(&clr.inner),
            _ => None,
        }
    }

    /// sets atom type
    pub fn set_atom_type(&mut self, at: TexSymbolType) {
        match *self {
            ParseNode::Symbol(ref mut sym) => sym.atom_type = at,
            ParseNode::Scripts(Scripts {
                base: Some(ref mut b),
                ..
            }) => {
                b.set_atom_type(at);
            }
            ParseNode::AtomChange(ref mut node) => node.at = at,
            ParseNode::Stack(Stack {
                ref mut atom_type, ..
            }) => *atom_type = at,
            _ => (),
        }
    }

    /// Get atom type of parse node
    pub fn atom_type(&self) -> TexSymbolType {
        match *self {
            ParseNode::Symbol(ref sym) => sym.atom_type,
            ParseNode::Delimited(_) => TexSymbolType::Inner,
            ParseNode::Radical(_) => TexSymbolType::Alpha,
            ParseNode::PlainText(_) => TexSymbolType::Alpha,
            ParseNode::GenFraction(_) => TexSymbolType::Inner,
            ParseNode::Group(_) => TexSymbolType::Alpha,
            ParseNode::Scripts(ref scr) => scr
                .base
                .as_ref()
                .map(|base| base.atom_type())
                .unwrap_or(TexSymbolType::Alpha),

            ParseNode::Rule(_) => TexSymbolType::Alpha,
            ParseNode::Kerning(_) => TexSymbolType::Transparent,
            ParseNode::Accent(ref acc) if acc.extend => TexSymbolType::Operator(true),
            ParseNode::Accent(ref acc) => acc
                .nucleus
                .first()
                .map(|acc| acc.atom_type())
                .unwrap_or(TexSymbolType::Alpha),

            ParseNode::Style(_) => TexSymbolType::Transparent,
            ParseNode::FontEffect(_) => TexSymbolType::Under,
            ParseNode::AtomChange(ref ac) => ac.at,
            ParseNode::Color(ref clr) => clr
                .inner
                .first()
                .map(|first| first.atom_type())
                .unwrap_or(TexSymbolType::Alpha),

            ParseNode::Array(_) => TexSymbolType::Inner,
            ParseNode::Stack(ref s) => s.atom_type,

            ParseNode::DummyNode(ref dummy) => dummy.at,
            ParseNode::ExtendedDelimiter(ExtendedDelimiter { symbol, .. }) => symbol.atom_type,
            // // DEPRECATED
            // ParseNode::Extend(_,_)   => AtomType::Inner,
        }
    }
}

/// if `contents` is a singleton containing a symbol, returns the symbol ; otherwise, None.
pub fn is_symbol(contents: &[ParseNode]) -> Option<Symbol> {
    if contents.len() != 1 {
        return None;
    }

    contents[0].is_symbol()
}
